[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_API_URL = "https://portcall-ai-backend-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200